### ISSUE TITLE
Update Zendesk footer to match Bootcamps site footer

### ISSUE THREAD

**Issue by briangrossman** [mitodl/bootcamps-zendesk-theme#3]
Update the footer for the [Zendesk theme](https://mitbootcamps.zendesk.com/hc/en-us) to match the rest of the Bootcamps site (see image below)

![image](https://user-images.githubusercontent.com/21342568/109855248-076b3500-7c26-11eb-9dbf-c680adaff016.png)

You can refer to these Zendesk themes for reference:
- xPRO - https://github.com/mitodl/mitxpro-zendesk-theme
- Micromasters - https://github.com/mitodl/micromasters-zendesk-theme

**Comment by arslanashraf7** [comment]
Closing it, This is done in https://github.com/mitodl/bootcamps-zendesk-theme/pull/5 and deployed!
