### ISSUE TITLE
Fix Hubspot code in Bootcamps Zendesk footer

### ISSUE THREAD

**Issue by briangrossman** [mitodl/bootcamps-zendesk-theme#6]
On Bootcamp's Zendesk portal the Sign Up For Email Updates form code needs to be swapped out. It's currently using a Hubspot form code that pipes the contacts into xPRO's CRM. It was accidentally been cloned over.

<img width="1751" alt="b8358500-e09b-11eb-97f0-16ba54c7b1bd" src="https://user-images.githubusercontent.com/21342568/125831303-6512e5ef-009a-46e7-a7fb-bae076731f0a.png">

Here is the correct form code:

```
<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	region: "na1",
	portalId: "6119748",
	formId: "2d798908-c195-4c0c-b075-a10b0c1b08f3"
});
</script>
```

Note: that Brian can update the theme when it's ready.

**Comment by arslanashraf7** [comment]
@briangrossman I believe we might not need a PR/Code change to fix the. The implementation of the theme contains custom configuration keys that can be set through Zendesk theme settings.

What you'd need to do is change the configuration setting values in Zendesk.

Once you visit the theme settings you should be able to see `Bootcamp footer elements` item on the left, upon clicking that you should be able to set the values for two keys:
- `hubspot_portal_id`
- `hubspot_footer_form_guid`

After applying the above settings, the theme should connect with the correct CRM.

**Comment by briangrossman** [comment]
@arslanashraf7 
Thanks! I forgot that's how it works. I just took care of this.
